### ISSUE TITLE
关于一个页面多个接口请求token失效的处理？

### ISSUE THREAD

**Issue by baoyachi** [xturbofan/TokenDemo#1]
请教一个问题：关于在进入首页需要验证token是否失效问题，要拿refreshToken刷新换取新token时候，多个接口同时请求时如何处理？

**Comment by fanturbo** [comment]
不好意思，没有看到，回复的有点晚。你说的这种情况就重新跳转到登录页面吧，然后重新刷新页面重新请求多个接口。或者就按照原先的处理方式，每一个都加retryWhen处理。这是我想到的解决方式。
